apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapp-deployment
  labels:
    app: userapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapp
  template:
    metadata:
      labels:
        app: userapp
    spec:
      containers:
      - name: userapp-container
        image: lowellhs/userapp
        env:
            - name: DB_HOST_USERAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_HOST_USERAPP
            - name: DB_PORT_USERAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_PORT_USERAPP
            - name: DB_NAME_USERAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_NAME_USERAPP
            - name: DB_USER_USERAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_USER_USERAPP
            - name: DB_PASS_USERAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_PASS_USERAPP
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        resources:
            requests:
                cpu: 100m
            limits:
                cpu: 120m
---
apiVersion: v1
kind: Service
metadata:
  name: userapp-service
spec:
  type: NodePort
  selector:
    app: userapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31001
---