apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-interface-deployment
  labels:
    app: main-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-interface
  template:
    metadata:
      labels:
        app: main-interface
    spec:
      containers:
      - name: main-interface-container
        image: lowellhs/main_interface
        env:
            - name: HOST_USERAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: HOST_USERAPP
            - name: HOST_TIMELINEAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: HOST_TIMELINEAPP
            - name: HOST_ADDFRIENDAPP
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: HOST_ADDFRIENDAPP
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: main-interface-service
spec:
  type: NodePort
  selector:
    app: main-interface
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000
---